// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_factors_stars
void get_factors_stars(List dimensions, bool curvilinear);
RcppExport SEXP _fstars_get_factors_stars(SEXP dimensionsSEXP, SEXP curvilinearSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dimensions(dimensionsSEXP);
    Rcpp::traits::input_parameter< bool >::type curvilinear(curvilinearSEXP);
    get_factors_stars(dimensions, curvilinear);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fstars_get_factors_stars", (DL_FUNC) &_fstars_get_factors_stars, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_fstars(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
