# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_interpolate_xy <- function(matrix, dimensions, x, y) {
    .Call('_fstars_rcpp_interpolate_xy', PACKAGE = 'fstars', matrix, dimensions, x, y)
}

rcpp_get_factors <- function(dimensions, CRS, curvilinear = FALSE) {
    .Call('_fstars_rcpp_get_factors', PACKAGE = 'fstars', dimensions, CRS, curvilinear)
}

rcpp_filter_matrix <- function(matrix, dimensions, CRS, ksize, stats, curvilinear = FALSE, adaptive = FALSE) {
    .Call('_fstars_rcpp_filter_matrix', PACKAGE = 'fstars', matrix, dimensions, CRS, ksize, stats, curvilinear, adaptive)
}

test_proj <- function() {
    .Call('_fstars_test_proj', PACKAGE = 'fstars')
}

