# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_factors_stars <- function(dimensions, curvilinear = FALSE) {
    invisible(.Call('_fstars_get_factors_stars', PACKAGE = 'fstars', dimensions, curvilinear))
}

test_proj <- function() {
    .Call('_fstars_test_proj', PACKAGE = 'fstars')
}

